print('Введите длину первого прямоугольника')
a = int(input()) 
print('Введите ширину первого прямоугольника')
b = int(input())
print('Введите длину второго прямоугольника')
c = int(input())
print('Введите длинну второго прямоугольника')
d = int(input())
if ((c-a)>=1 and (d-b)>=1) :print('Да')
else: 
    if ((c-d)>=1 and (d-a)>=1) :print('Да')
    else:  print('Нет')
